# Generated by Django 4.2.7 on 2023-11-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("emailserv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emailserv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="Время рассылки")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("1", "Раз в день"),
                            ("2", "Раз в неделю"),
                            ("3", "Раз в месяц"),
                        ],
                        default="1",
                        verbose_name="Период рассылки",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Статус рассылки"
                    ),
                ),
                (
                    "emails",
                    models.ManyToManyField(
                        to="users.user", verbose_name="Пользователи"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emailserv.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="logs",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="emailserv.emailserv",
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.DeleteModel(
            name="EmailDistribution",
        ),
    ]
